name: Dockerize and Deploy Laravel Project to Minikube

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo, zip

      - name: Install dependencies
        working-directory: ./Backend
        run: composer install --no-dev --optimize-autoloader

      - name: Copy .env file
        working-directory: Backend
        run: |
          pwd
          cp .env.example .env
          php artisan key:generate
          php artisan jwt:secret

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          pwd
          ls -la
          docker build -t ${{ secrets.DOCKER_USERNAME }}/laravel_app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/laravel_app:${{ github.sha }}

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.7.0
        with:
          minikube-version: 'latest'
          kubernetes-version: 'v1.24.0'
          driver: docker

      - name: Deploy to Kubernetes
        run: |
          kubectl create deployment laravel-deployment --image=${{ secrets.DOCKER_USERNAME }}/laravel_app:${{ github.sha }}
          kubectl expose deployment laravel-deployment --type=NodePort --port=80 --target-port=9000

      - name: Get Minikube service URL
        id: get-url
        run: echo "::set-output name=url::$(minikube service laravel-deployment --url)"

      - name: Output service URL
        run: echo "Laravel service is running at ${{ steps.get-url.outputs.url }}"

