
name: Dockerize Laravel Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, pdo, zip

    
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

    
      - name: Copy .env file
        run: cp /Backend/.env.example /Backend/.env

    
      - name: Generate application key
        run: php artisan key:generate

      - name: Generate application JWT
        run: php artisan jwt:secret

    
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/laravel_app:${{ github.sha }} .

    
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/laravel_app:${{ github.sha }}
